### ISSUE TITLE
Size text to perfectly fit to container using both container width and height. 

### ISSUE THREAD

**Issue by BernardMyburgh** [DanielHoffmann/jquery-bigtext#9]
Hi,

Is it possible to fit text perfectly to a container so that it stays / resizes fluidly within a div and does not extend the font-size beyond the container height? Say you have "Name Surname", in a div thats 100px wide and 20px high, it fits perfectly. If you have just "Name", the text becomes huge and extends beyond the height of 20px high box. Is there a 'constrain to container height' option?

Thank you for the great plugin!

Bernard

**Comment by DanielHoffmann** [comment]
Hello Bernard, by default the text never overflows the container div so in your example the "Name" would appear bigger than "Name Surname", but never bigger than 20px in height or 100px in width (whatever happens first).

There is an option named limitingDimension that changes this, by default it is set to "both", but if you set it to "width" the 20px height value is ignored and the text will resize until it fits the width of the widget, meaning it can (but not always) grow bigger than 20px in height.

**Comment by BernardMyburgh** [comment]
Thank you so much for getting back to me, I've got it working! Few of my notes:

1. Make sure there are no jquery errors right before the code, else it wont work.
2. In your "Examples" and "Usage", you first use $("#span"), then you use $("#div"), it was confusing. 
3. Your link (https://rawgithub.com/DanielHoffmann/jquery-bigtext/master/examples/examples.html) to see more examples is broken.

Else this is perfectly exactly what I was looking for. Thank you!

**Comment by DanielHoffmann** [comment]
Hello Bernard,

1. Well it is javascript if there is an error the execution stops, unless you mean there is an error inside the plugin?
2. Yes that is wrong, I will fix it right away. Thanks for noticing.
3. Indeed the README.md  is outdated, I moved the documentation from rawgit to githubpages, the right link is: [http://danielhoffmann.github.io/jquery-bigtext/]

I will update the README.md and sorry for the mistakes, I hope you like my plugin.
